name: profit_v3
description: "App oficial da Profit Laboratórios"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  change_app_package_name: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/contatos/
    - assets/social/
    - assets/

  fonts:
      - family: MASQUE
        fonts:
          - asset: assets/fonts/MASQUE.ttf